name: Release

on:
  push:
    tags:
      - 'v*'  # Only trigger on version tags

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install .[testing]

      - name: Run tests
        run: python3 tests/test.py

      - name: Build package
        if: ${{ matrix.python-version == '3.10' && matrix.os == 'ubuntu-latest' }}
        run: python setup.py sdist bdist_wheel

      - name: Upload to PyPI
        if: ${{ matrix.python-version == '3.10' && matrix.os == 'ubuntu-latest' }}
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          pip install twine
          twine upload dist/*

      - name: Remove previous builds
        if: ${{ matrix.python-version == '3.10' && matrix.os == 'ubuntu-latest' }}
        run: rm -rf dist/*

